-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 22:57:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema presupuestos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema presupuestos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `presupuestos` DEFAULT CHARACTER SET utf8 ;
USE `presupuestos` ;

-- -----------------------------------------------------
-- Table `presupuestos`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presupuestos`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `presupuestos`.`budgets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presupuestos`.`budgets` (
  `budget_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`budget_id`),
  INDEX `fk_budgets_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_budgets_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `presupuestos`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `presupuestos`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presupuestos`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `budget_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `class` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `fk_categories_budgets_idx` (`budget_id` ASC),
  CONSTRAINT `fk_categories_budgets`
    FOREIGN KEY (`budget_id`)
    REFERENCES `presupuestos`.`budgets` (`budget_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `presupuestos`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presupuestos`.`items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_items_categories_idx` (`category_id` ASC),
  CONSTRAINT `fk_items_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `presupuestos`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `presupuestos`.`values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presupuestos`.`values` (
  `value_id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `date` DATE NOT NULL,
  `class` VARCHAR(20) NOT NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`value_id`),
  INDEX `fk_values_items_idx` (`item_id` ASC),
  CONSTRAINT `fk_values_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `presupuestos`.`items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
